version: 2

project_name: envsecrets

before:
  hooks:
    - go mod tidy

builds:
  - id: envsecrets
    binary: envsecrets
    main: ./cmd/envsecrets
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/charliek/envsecrets/internal/version.Version={{.Version}}
      - -X github.com/charliek/envsecrets/internal/version.GitCommit={{.ShortCommit}}
      - -X github.com/charliek/envsecrets/internal/version.BuildDate={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: charliek
    name: envsecrets
  draft: false
  prerelease: auto
  mode: replace

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
